### ISSUE TITLE
[BUG] - 403 Code  have no permission to access this resource

### ISSUE THREAD

**Issue by Hikohikoyan** [blueprintue/feedback#27]
## Description
> Hi all,I'm recently work on blueprintue  , using Chrome and Edge. Accepted the cookies. Logged in.
> It's all good 3 days ago but suddenly  when I tried to view profiles, I Got this 403 Error Code,
> 
> 
> And I tried to clean teh cookies and some other,but it doesn't help.
> My friends and my iphone safari (and chrome on ios ) have no error,but on PC it's bad.

I searched the error log and I found out this, hope it could help!

https://developer.chrome.com/docs/lighthouse/best-practices/doctype/

https://www.reddit.com/r/chrome/comments/qhhg0m/chrome_issue_page_layout_may_be_unexpected_due_to/?rdt=47557&onetap_auto=true

https://stackoverflow.com/questions/20594749/how-to-disable-quirk-mode

https://stackoverflow.com/questions/7168288/page-stuck-in-quirks-mode

By the way , I could correctly open the web sometimes ……
Report this just in case!~
 
## Screenshots
>Hope my screenshots would help explain problem.

![image](https://github.com/blueprintue/feedback/assets/42509584/b341db3e-ce12-4813-b441-8ad4880fc80d)
![image](https://github.com/blueprintue/feedback/assets/42509584/4e9a939c-75aa-41f1-9049-e8232c5ad95a)

## Versions
 - OS: [e.g. Windows 11]
 - Browser Version: [Chrome  118.0.5993.89]

**Comment by rancoud** [comment]
Hello,

Can you retry now?
About Quirks Mode for a 403 (same for 40x or 50x) page is normal because it's using the default Apache output error.

**Comment by rancoud** [comment]
@Hikohikoyan do you have some news?

**Comment by rancoud** [comment]
Issue closed because no news.
