### ISSUE TITLE
[BUG] - Postgres database initialization

### ISSUE THREAD

**Issue by Nemirtingas** [blueprintue/feedback#29]
## Description
> Postgres database initialization

## Steps to reproduce this issue
1. Use pgsql driver

## Expected behavior
> SQL dump works

## Actual behavior
> SQL dump has invalid syntax for postgres

## Additional context
Attached my working postgres initialization script.

[postgres_dump.zip](https://github.com/blueprintue/feedback/files/13375075/postgres_dump.zip)

The SQL code of the self-hosted website needs tweaks to work with postgres, but at least, the database initialization works now.

These are the tweaks:
```
# Replace UTC_TIMESTAMP() by timezone('utc', now())
grep 'UTC_TIMESTAMP()' -Ri . | awk -F: '{ print $1 }' | while read f; do sed -i "s|UTC_TIMESTAMP()|timezone('utc', now())|i" "$f"; done

# Replace LIMIT :offset, :count by LIMIT :count OFFSET :offset
grep 'LIMIT :offset, :count' -Ri . | awk -F: '{ print $1 }' | while read f; do sed -i 's/LIMIT :offset, :count/LIMIT :count OFFSET :offset/i' "$f"; done
```

Replace Field.convertToDateTime to handle milliseconds ('.u')
```
    protected function convertToDatetime($value): string
    {
        $datetime = (string) $value;

        if ($this->isInvalidPattern('/' . $this->patternDate . ' ' . $this->patternTime . '/', $datetime)) {
            throw new FieldException('Invalid datetime value');
        }

        $format = 'Y-m-d H:i:s';
        if (strpos($value, '.') !== false) {
          $format .= '.u';
        }
        $datetime = DateTime::createFromFormat($format, $datetime);
        if ($datetime === false) {
            throw new FieldException('Invalid date value');
        }

        return $datetime->format('Y-m-d H:i:s');
    }
```

**Comment by rancoud** [comment]
Hello,

As indicated in the [requirements](https://github.com/blueprintue/blueprintue-self-hosted-edition#minimum-requirements) I only supports MySql or MariaDB.
However I have left the possible values supported by https://github.com/rancoud/Database in the documentation.
That's why dump files and sql queries was not working with Postgres.

So maybe I should put a warning message in the README so that users only use the `mysql` driver for the database.

**Comment by Nemirtingas** [comment]
Runs fine on my Postgres instance, so I'm fine with it.
