### ISSUE TITLE
[BUG] - Lose Niagara System node connection

### ISSUE THREAD

**Issue by CheapMeow** [blueprintue/feedback#32]
## Description

I paste my niagara module blueprint and find all node connections are lost.

Example:

https://blueprintue.com/blueprint/la5wvvdc/

But I also find someone else doesn't have this problem.

Example:

https://blueprintue.com/blueprint/gq8ri2to/

## Steps to reproduce this issue
1. See two examples

## Expected behavior

All node connections are preserved.

## Actual behavior

All node connections are lost.

## Screenshots

![image](https://github.com/blueprintue/feedback/assets/88229072/da814893-1ca3-402e-9280-ec374455d3f6)

## Versions
 - OS: [Windows 11]
 - Browser Version: [Chrome Version 120.0.6099.130 (Official Build) (64-bit)]

**Comment by rancoud** [comment]
Hello and thanks for your issue.
Problem is fixed, if you don't it see refresh the cache.
