### ISSUE TITLE
[BUG] - Error in material blueprint copying function

### ISSUE THREAD

**Issue by chendongde310** [blueprintue/feedback#36]
## Description
> While trying to copy any material blueprint node in the Website , an error message pops up, indicating a TypeError. This issue seems to be related to the `generateText` function not being recognized as a function for nodes, which interrupts the copy action.

## Steps to Reproduce this Issue
1. Open the Website and navigate to the material blueprint section.
2. Select any material blueprint node.
3. Attempt to copy the selected node using the copy functionality.
4. The error message is displayed, and the copy action fails.

## Expected Behavior
> I expected that the selected material blueprint node would be copied successfully without any errors, allowing for efficient workflow within the application.

## Actual Behavior
> Instead of copying the node successfully, an error message is displayed: "Uncaught TypeError: this.nodes[a].generateText is not a function at NMaterialGraphNode.generateTextForUnreal (render.js:30:2650) at Editor.eventCopyNodesToClipboard (render.js:7:4641) at Bus.emit (render.js:6:720) at Interactor.copyNodesSelectedInClipboard (render.js:8:23415) at Interactor.eventCopyNodes (render.js:8:12795)". This prevents the node from being copied as intended.
  

## Additional Context
> This issue disrupts the material blueprint editing workflow significantly, as copying nodes is a fundamental part of creating and editing material blueprints. A quick resolution would be greatly appreciated.

**Comment by chendongde310** [comment]
![Uploading QQ截图20240307003941.png…]()

**Comment by chendongde310** [comment]
![QQ截图20240307003941](https://github.com/blueprintue/feedback/assets/19258984/872462a3-005a-4223-ba64-cc5d226cf12d)

**Comment by rancoud** [comment]
Thank you for your issue.
I've written a patch for this and deployed it to blueprintue and the self-hosted edition as well.
If you don't see it, please clear your browser cache.
